version: '3.9'

services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - /auth_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=auth_pass
      - POSTGRES_USER=auth_user
      - POSTGRES_DB=auth_db
  redis:
    image: redis
    ports:
      - '6379:6379'
    restart: always
